<?php
// i18n-map.php @generated by automattic/jetpack-composer-plugin
return array(
  'domain' => 'jetpack',
  'type' => 'plugins',
  'packages' => array(
    'jetpack-account-protection' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-account-protection',
      'ver' => '0.3.1-alpha1777322605',
    ),
    'jetpack-activity-log' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-activity-log',
      'ver' => '0.2.0-alpha1777558224',
    ),
    'jetpack-admin-ui' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-admin-ui',
      'ver' => '0.8.2-alpha1777322605',
    ),
    'jetpack-assets' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-assets',
      'ver' => '4.3.34-alpha1777322605',
    ),
    'jetpack-backup-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-backup',
      'ver' => '4.2.54-alpha1777322605',
    ),
    'jetpack-blaze' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-blaze',
      'ver' => '0.27.16-alpha1777322605',
    ),
    'jetpack-block-delimiter' => array(
      'path' => 'jetpack_vendor/automattic/block-delimiter',
      'ver' => '0.3.6-alpha1777322605',
    ),
    'jetpack-boost-core' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-boost-core',
      'ver' => '0.4.4-alpha1777322605',
    ),
    'jetpack-boost-speed-score' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-boost-speed-score',
      'ver' => '0.4.14-alpha1777322605',
    ),
    'jetpack-classic-theme-helper' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-classic-theme-helper',
      'ver' => '0.14.25-alpha1777322605',
    ),
    'jetpack-compat' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-compat',
      'ver' => '4.0.2-alpha1777322605',
    ),
    'jetpack-config' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-config',
      'ver' => '3.1.2-alpha1777322605',
    ),
    'jetpack-connection' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-connection',
      'ver' => '8.3.3-alpha1777900078',
    ),
    'jetpack-explat' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-explat',
      'ver' => '0.4.22-alpha1777322605',
    ),
    'jetpack-external-connections' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-external-connections',
      'ver' => '0.1.26-alpha1777322605',
    ),
    'jetpack-external-media' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-external-media',
      'ver' => '0.8.15-alpha1777322605',
    ),
    'jetpack-forms' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-forms',
      'ver' => '7.21.0-alpha1777551255',
    ),
    'jetpack-image-cdn' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-image-cdn',
      'ver' => '0.7.25-alpha1777322605',
    ),
    'jetpack-import' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-import',
      'ver' => '0.9.16-alpha1777322605',
    ),
    'jetpack-ip' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-ip',
      'ver' => '0.4.11-alpha1777322605',
    ),
    'jetpack-jitm' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-jitm',
      'ver' => '4.3.32-alpha1777322605',
    ),
    'jetpack-jwt' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-jwt',
      'ver' => '0.2.3-alpha1777322605',
    ),
    'jetpack-licensing' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-licensing',
      'ver' => '3.1.6-alpha1777322605',
    ),
    'jetpack-masterbar' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-masterbar',
      'ver' => '0.27.23-alpha1777322605',
    ),
    'jetpack-my-jetpack' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-my-jetpack',
      'ver' => '5.36.0-alpha1777903151',
    ),
    'jetpack-newsletter' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-newsletter',
      'ver' => '0.8.6-alpha1777322605',
    ),
    'jetpack-password-checker' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-password-checker',
      'ver' => '0.4.10-alpha1777322605',
    ),
    'jetpack-paypal-payments' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-paypal-payments',
      'ver' => '0.6.18-alpha1777322605',
    ),
    'jetpack-plugins-installer' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-plugins-installer',
      'ver' => '0.5.8-alpha1777322605',
    ),
    'jetpack-post-list' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-post-list',
      'ver' => '0.9.16-alpha1777322605',
    ),
    'jetpack-post-media' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-post-media',
      'ver' => '0.1.2-alpha1777322605',
    ),
    'jetpack-protect-models' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-protect-models',
      'ver' => '0.6.2-alpha1777322605',
    ),
    'jetpack-protect-status' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-protect-status',
      'ver' => '0.7.9-alpha1777322605',
    ),
    'jetpack-publicize-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-publicize',
      'ver' => '0.79.0-alpha1777897462',
    ),
    'jetpack-search-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-search',
      'ver' => '0.58.0-alpha1777877665',
    ),
    'jetpack-stats' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-stats',
      'ver' => '0.19.0-alpha1777583813',
    ),
    'jetpack-stats-admin' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-stats-admin',
      'ver' => '0.31.2-alpha1777322605',
    ),
    'jetpack-subscribers-dashboard' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-subscribers-dashboard',
      'ver' => '0.5.5-alpha1777322605',
    ),
    'jetpack-sync' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-sync',
      'ver' => '4.37.0-alpha1777885977',
    ),
    'jetpack-videopress-pkg' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-videopress',
      'ver' => '0.36.7-alpha1777565325',
    ),
    'jetpack-waf' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-waf',
      'ver' => '0.28.3-alpha1777322605',
    ),
    'jetpack-wp-abilities' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-wp-abilities',
      'ver' => '0.1.0-alpha1777322605',
    ),
    'jetpack-wp-build-polyfills' => array(
      'path' => 'jetpack_vendor/automattic/jetpack-wp-build-polyfills',
      'ver' => '0.1.6-alpha1777322605',
    ),
    'woocommerce-analytics' => array(
      'path' => 'jetpack_vendor/automattic/woocommerce-analytics',
      'ver' => '0.16.3',
    ),
  ),
);
